B = ord('B')
C = ord('C')
D = ord('D')
b = ord('b')
c = ord('c')
d = ord('d')
zero = ord('0')
one = ord('1')
two = ord('2')
dollar_sign = ord('$')
star_sign = ord('*')
plus = ord('+')
space = ord(' ')

print('Integer equivalent of \'B\' is', B)
print('Integer equivalent of \'C\' is', C)
print('Integer equivalent of \'D\' is', D)
print('Integer equivalent of \'b\' is', b)
print('Integer equivalent of \'c\' is', c)
print('Integer equivalent of \'d\' is', d)
print('Integer equivalent of \'0\' is', zero)
print('Integer equivalent of \'1\' is', one)
print('Integer equivalent of \'2\' is', two)
print('Integer equivalent of \'$\' is', dollar_sign)
print('Integer equivalent of \'*\' is', star_sign)
print('Integer equivalent of \'+\' is', plus)
print('Integer equivalent of the space character is', space)